### PR TITLE
Resolve #4

### LINKED ISSUE #4: Font and taskbar color bug
If you use this plugin while using colors from the wallpapers, the taskbar doesn't change color and some font colors are black in dark colors, making them unreadable. I think it has to do with using the custom option.

### PR DESCRIPTION
**Pull request by BSoDium**
The current implementation of the theme toggling updates the registry values at `Software\Microsoft\Windows\CurrentVersion\Themes\Personalize` which is not enough to update Windows explorer's state. There are currently two solutions to this problem:

1. restarting the file explorer, which works, but is a bit brutal (killing the windows file explorer renders the window manager and taskbar unusable for a couple seconds
2. elegantly synchronising the explorer via an existing workaround, which I am currently trying to find. A correct implementation in C# of such a workaround can be found [here](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/blob/e85e18722e7811258443669c803a375b93d14053/AutoDarkModeSvc/Handlers/ThemeFiles/ThemeFile.cs#L444)

I have started writing tests for the `handler` module, and am currently working on solving the theme sync issue (#4).

### CODE REVIEW

**Comment by BSoDium** [comment]
After examining the implementation of [Windows Auto Dark Mode](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode) and with the assistance of @Spiritreader, I have concluded that there are three possible ways to achieve a working Windows theme switcher:

1. One option is to include Auto Dark Mode (ADM) binaries in the plugin and manually update the repository when Windows releases a breaking change. However, this increases the plugin size by about 100 MB and requires starting and shutting down an ADM service instance on each theme change, which is extremely heavy performance-wise (incidentally nearly as brutal as restarting the file explorer). This solution is less graceful but makes the extension fully portable and independent.

2. Another option is to require the user to have the ADM service running in the background and use the shell to control it and switch themes. This is constraining as it requires third-party software to be installed, but it entirely removes the need for binaries to be packaged with the plugin.

3. A third option is to keep both modes: the current (broken) registry editing, and the optional ADM shell calls (which can be enabled manually or automatically if ADM is detected). This still requires the user to install ADM separately, but they can choose not to if they're fine with their taskbar not matching the system theme from time to time.

@Garulf I'd love your insight on this, what do you think?

**Comment by Garulf** [comment]
Sorry I've been busy with a couple projects and haven't had a chance to respond. 

Ideally the plugin can be used without binary dependencies. As you note this increases the file size and we'd have to make sure we respect any licenses. 

When I have some time I'd like to do some research on what system calls are needed and see if they can be exposed in Python and called directly. Failing this I think requiring the user to have an installation of ADM is fine.


EDIT: This seems to be a problem even for ADM as they state here: https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Known-limitations

**Comment by BSoDium** [comment]
No worries, I totally agree with you, but from what I've seen, ADM's implementation is far more advanced than the current one. The binaries I pushed were merely an attempt at fixing the behavior in a quick and dirty way, I will be removing them in my next commit. 
Still I believe ADM's support for MS Windows's shady theme switching "API" is more reliable than Flow Launcher's community's.
Should this PR add a temporary ADM integration as stated in option 3 in the meantime? I believe that to be a reasonably stable fix.

**Comment by Garulf** [comment]
I'm looking at their source code now to see how they toggle dark mode. It doesn't seem impossible to get this working. I'll let you know if I have a break through.

**Comment by Spiritreader** [comment]
> I'm looking at their source code now to see how they toggle dark mode. It doesn't seem impossible to get this working. I'll let you know if I have a break through.

I can assure you it's not as simple as you think.
Impossible? No, but Windows theme switching is incredibly bugged right now and I pulled multiple hairs out to get to the state we're at right now.

**Comment by Garulf** [comment]
> > I'm looking at their source code now to see how they toggle dark mode. It doesn't seem impossible to get this working. I'll let you know if I have a break through.
> 
> I can assure you it's not as simple as you think. Impossible? No, but Windows theme switching is incredibly bugged right now and I pulled multiple hairs out to get to the state we're at right now.

You are correct. Handling the theme switching in its current state would take some considerable effort with what is suppose to be a very simple shortcut to let the user switch a color theme when they want.

**Comment by Garulf** [comment]
> Should this PR add a temporary ADM integration as stated in option 3 in the meantime? I believe that to be a reasonably stable fix.

@BSoDium Seems reasonable to me. I've chosen to stay on Windows 10 for the time being so I do not experience any major bugs with the plugin in its current state.

**Comment by Spiritreader** [comment]
> > > I'm looking at their source code now to see how they toggle dark mode. It doesn't seem impossible to get this working. I'll let you know if I have a break through.
> > 
> > 
> > I can assure you it's not as simple as you think. Impossible? No, but Windows theme switching is incredibly bugged right now and I pulled multiple hairs out to get to the state we're at right now.
> 
> You are correct. Handling the theme switching in its current state would take some considerable effort with what is suppose to be a very simple shortcut to let the user switch a color theme when they want.

Sadly yes. That's why I believe that calling the ADM API would make more sense if users desire to use the flow launcher to change themes. This is also what @BSoDium was referring to in his propsoal.

> Ideally the plugin can be used without binary dependencies. As you note this increases the file size and we'd have to make sure we respect any licenses.

I would agree that provisioning ADM as binary is unfavorable and I wouldn't recommend it, but it could potentially make sense to have an option to use ADM as theme switching mechanism for those that want that functionality by using the API and requiring users to have it installed by themselves.

Beside that, there are other binary solutions (ADM's 22H2 compatible theme switching mechanism itself uses a combination of findings from KawaiiThemeSwitcher and SecureUXTheme), but it's still required to modify those applications to synchronize with the active theme and patch the theme file to decrease the chance of failed theme switches or unwanted changes in system style.

In the end my hopes are that Microsoft opens up the entirety of Windows theme switching, or at least changing system and app modes in the very near future.

**Comment by BSoDium** [comment]
Great, I'll be resuming development pretty soon then 🚀
Thanks for the insight!

**Comment by Spiritreader** [comment]
> Great, I'll be resuming development pretty soon then 🚀 Thanks for the insight!

That being said ADM still functions a bit differently than this plugin. The toggle allows controlling system and apps theme individually, whereas auto dark mode switches the entire theme based on a predefined config.

It's up to @Garulf if at all, and in what capacity any kind of integration should take place.

**Comment by Garulf** [comment]
> That being said ADM still functions a bit differently than this plugin. The toggle allows controlling system and apps theme individually, whereas auto dark mode switches the entire theme based on a predefined config.
> 
> It's up to @Garulf if at all, and in what capacity any kind of integration should take place.

The main focus of the plugin was to switch the entire theme with one press. The options for individual app and system theme were only included because I had to implement those methods anyway and figured I'd expose them as extra options.

I dont think anyone is really using different themes for their Apps and System.

**Comment by Spiritreader** [comment]
In case it is useful, I've created a quick gist that implements the ADM api via named pipes in python.

https://gist.github.com/Spiritreader/7ee8b1800ac6abe6d4b19297133b5f45

With
```python
send_message_and_get_reply(message)
```


any parameter found in the [API-documentation](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Command-line-arguments-%7C-parameters) can be passed as message, for example `--dark` and `--light`.

pywin32 is required,

**Comment by Garulf** [comment]
> In case it is useful, I've created a quick gist that implements the ADM api via named pipes in python.
> 
> https://gist.github.com/Spiritreader/7ee8b1800ac6abe6d4b19297133b5f45
> 
> With
> 
> ```python
> send_message_and_get_reply(message)
> ```
> 
> any parameter found in the [API-documentation](https://github.com/AutoDarkMode/Windows-Auto-Night-Mode/wiki/Command-line-arguments-%7C-parameters) can be passed as message, for example `--dark` and `--light`.

I am not able to test right now, but it looks good! 👍 

> pywin32 is required,

This dependency may present a problem however. pywin32 uses binary code that compiles to whatever Python version it was installed with. 

This makes it difficult to distribute as the user *must* use the exact Python version you installed with.

**Comment by Spiritreader** [comment]
> This makes it difficult to distribute as the user must use the exact Python version you installed with.

Hmm yes this could be a problem.

https://gist.github.com/Spiritreader/9e34bc5011c408f7e2f7118ab35c9ba8

This new gist just uses files and has no external dependencies at all

**Comment by Garulf** [comment]
> Hmm yes this could be a problem.
> 
> https://gist.github.com/Spiritreader/9e34bc5011c408f7e2f7118ab35c9ba8
> 
> This new gist just uses files and has no external dependencies at all

Oh that's cool!

**Pull request closed without merging**
